# Generated by Django 3.2.6 on 2021-11-20 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoFilmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('filme1', models.CharField(max_length=30)),
                ('filme2', models.CharField(max_length=30)),
                ('filme3', models.CharField(max_length=30)),
                ('filme4', models.CharField(max_length=30)),
                ('filme5', models.CharField(max_length=30)),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 11, 20, 14, 33, 39, 580306), verbose_name='Lista publicada em')),
            ],
        ),
    ]
