# Generated by Django 3.2.9 on 2021-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_url_url_scraper_url_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_scraper',
            name='URL_save',
            field=models.CharField(max_length=50),
        ),
    ]
